# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20171024_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='transgoodsinfo',
            name='enabled_key',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transinfo',
            name='enabled_key',
            field=models.IntegerField(default=0),
        ),
    ]
