# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-26 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20171026_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='transinfo',
            name='contract_name_text',
            field=models.CharField(default=0, max_length=100, verbose_name='合同编号'),
            preserve_default=False,
        ),
    ]
