# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costinfo',
            name='cost_name_text',
            field=models.CharField(max_length=100, verbose_name='费用名称'),
        ),
    ]
